/* tslint:disable */
/* eslint-disable */
/**
 * go_app/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1DeleteResponse
 */
export interface V1DeleteResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof V1DeleteResponse
     */
    errors?: Array<string>;
}

/**
 * Check if a given object implements the V1DeleteResponse interface.
 */
export function instanceOfV1DeleteResponse(value: object): boolean {
    return true;
}

export function V1DeleteResponseFromJSON(json: any): V1DeleteResponse {
    return V1DeleteResponseFromJSONTyped(json, false);
}

export function V1DeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function V1DeleteResponseToJSON(value?: V1DeleteResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'errors': value['errors'],
    };
}

