/* tslint:disable */
/* eslint-disable */
/**
 * go_app/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1HelloType } from './V1HelloType';
import {
    V1HelloTypeFromJSON,
    V1HelloTypeFromJSONTyped,
    V1HelloTypeToJSON,
} from './V1HelloType';

/**
 * 
 * @export
 * @interface V1Hello
 */
export interface V1Hello {
    /**
     * 
     * @type {string}
     * @memberof V1Hello
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof V1Hello
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1Hello
     */
    updatedAt?: Date;
    /**
     * 
     * @type {V1HelloType}
     * @memberof V1Hello
     */
    helloType?: V1HelloType;
    /**
     * 
     * @type {string}
     * @memberof V1Hello
     */
    personName?: string;
}

/**
 * Check if a given object implements the V1Hello interface.
 */
export function instanceOfV1Hello(value: object): boolean {
    return true;
}

export function V1HelloFromJSON(json: any): V1Hello {
    return V1HelloFromJSONTyped(json, false);
}

export function V1HelloFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Hello {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'helloType': json['hello_type'] == null ? undefined : V1HelloTypeFromJSON(json['hello_type']),
        'personName': json['person_name'] == null ? undefined : json['person_name'],
    };
}

export function V1HelloToJSON(value?: V1Hello | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'hello_type': V1HelloTypeToJSON(value['helloType']),
        'person_name': value['personName'],
    };
}

