/* tslint:disable */
/* eslint-disable */
/**
 * go_app/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Todo } from './V1Todo';
import {
    V1TodoFromJSON,
    V1TodoFromJSONTyped,
    V1TodoToJSON,
} from './V1Todo';

/**
 * 
 * @export
 * @interface V1ListTodosResponse
 */
export interface V1ListTodosResponse {
    /**
     * 
     * @type {Array<V1Todo>}
     * @memberof V1ListTodosResponse
     */
    todos?: Array<V1Todo>;
    /**
     * 
     * @type {number}
     * @memberof V1ListTodosResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the V1ListTodosResponse interface.
 */
export function instanceOfV1ListTodosResponse(value: object): boolean {
    return true;
}

export function V1ListTodosResponseFromJSON(json: any): V1ListTodosResponse {
    return V1ListTodosResponseFromJSONTyped(json, false);
}

export function V1ListTodosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListTodosResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'todos': json['todos'] == null ? undefined : ((json['todos'] as Array<any>).map(V1TodoFromJSON)),
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function V1ListTodosResponseToJSON(value?: V1ListTodosResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'todos': value['todos'] == null ? undefined : ((value['todos'] as Array<any>).map(V1TodoToJSON)),
        'totalPages': value['totalPages'],
    };
}

