/* tslint:disable */
/* eslint-disable */
/**
 * go_app/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Todo } from './V1Todo';
import {
    V1TodoFromJSON,
    V1TodoFromJSONTyped,
    V1TodoToJSON,
} from './V1Todo';

/**
 * 
 * @export
 * @interface V1Todos
 */
export interface V1Todos {
    /**
     * 
     * @type {Array<V1Todo>}
     * @memberof V1Todos
     */
    todos?: Array<V1Todo>;
}

/**
 * Check if a given object implements the V1Todos interface.
 */
export function instanceOfV1Todos(value: object): boolean {
    return true;
}

export function V1TodosFromJSON(json: any): V1Todos {
    return V1TodosFromJSONTyped(json, false);
}

export function V1TodosFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Todos {
    if (json == null) {
        return json;
    }
    return {
        
        'todos': json['todos'] == null ? undefined : ((json['todos'] as Array<any>).map(V1TodoFromJSON)),
    };
}

export function V1TodosToJSON(value?: V1Todos | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'todos': value['todos'] == null ? undefined : ((value['todos'] as Array<any>).map(V1TodoToJSON)),
    };
}

