/* tslint:disable */
/* eslint-disable */
/**
 * go_app/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const V1TodoType = {
    Generic: 'TODO_GENERIC',
    Specific: 'TODO_SPECIFIC'
} as const;
export type V1TodoType = typeof V1TodoType[keyof typeof V1TodoType];


export function V1TodoTypeFromJSON(json: any): V1TodoType {
    return V1TodoTypeFromJSONTyped(json, false);
}

export function V1TodoTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TodoType {
    return json as V1TodoType;
}

export function V1TodoTypeToJSON(value?: V1TodoType | null): any {
    return value as any;
}

