/* tslint:disable */
/* eslint-disable */
/**
 * go_app/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1TodoType } from './V1TodoType';
import {
    V1TodoTypeFromJSON,
    V1TodoTypeFromJSONTyped,
    V1TodoTypeToJSON,
} from './V1TodoType';

/**
 * 
 * @export
 * @interface V1Todo
 */
export interface V1Todo {
    /**
     * 
     * @type {string}
     * @memberof V1Todo
     */
    id?: string;
    /**
     * 
     * @type {V1TodoType}
     * @memberof V1Todo
     */
    todoType?: V1TodoType;
    /**
     * 
     * @type {string}
     * @memberof V1Todo
     */
    todoName?: string;
    /**
     * 
     * @type {number}
     * @memberof V1Todo
     */
    priority?: number;
    /**
     * 
     * @type {boolean}
     * @memberof V1Todo
     */
    completed?: boolean;
}

/**
 * Check if a given object implements the V1Todo interface.
 */
export function instanceOfV1Todo(value: object): boolean {
    return true;
}

export function V1TodoFromJSON(json: any): V1Todo {
    return V1TodoFromJSONTyped(json, false);
}

export function V1TodoFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Todo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'todoType': json['todo_type'] == null ? undefined : V1TodoTypeFromJSON(json['todo_type']),
        'todoName': json['todo_name'] == null ? undefined : json['todo_name'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'completed': json['completed'] == null ? undefined : json['completed'],
    };
}

export function V1TodoToJSON(value?: V1Todo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'todo_type': V1TodoTypeToJSON(value['todoType']),
        'todo_name': value['todoName'],
        'priority': value['priority'],
        'completed': value['completed'],
    };
}

