/* tslint:disable */
/* eslint-disable */
/**
 * go_app/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Todo } from './V1Todo';
import {
    V1TodoFromJSON,
    V1TodoFromJSONTyped,
    V1TodoToJSON,
} from './V1Todo';

/**
 * 
 * @export
 * @interface V1UpsertTodosRequest
 */
export interface V1UpsertTodosRequest {
    /**
     * 
     * @type {Array<V1Todo>}
     * @memberof V1UpsertTodosRequest
     */
    data?: Array<V1Todo>;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1UpsertTodosRequest
     */
    fields?: Array<string>;
}

/**
 * Check if a given object implements the V1UpsertTodosRequest interface.
 */
export function instanceOfV1UpsertTodosRequest(value: object): boolean {
    return true;
}

export function V1UpsertTodosRequestFromJSON(json: any): V1UpsertTodosRequest {
    return V1UpsertTodosRequestFromJSONTyped(json, false);
}

export function V1UpsertTodosRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UpsertTodosRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(V1TodoFromJSON)),
        'fields': json['fields'] == null ? undefined : json['fields'],
    };
}

export function V1UpsertTodosRequestToJSON(value?: V1UpsertTodosRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(V1TodoToJSON)),
        'fields': value['fields'],
    };
}

